stages:
  - deploy

deploy-dev:
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_PRODUCTION_API_KEY
    HEROKU_APP: thebutler-api-dev
  before_script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y heroku-toolbelt
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - develop
    - master

build-prod:
  stage: build
  allow_failure: false
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/thebutler.jar

deploy-prod:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region us-east-1
    - pip install awsebcli --upgrade --user
    - ~/.local/bin/eb use thebutler-api-prod
    - ~/.local/bin/eb deploy
  dependencies:
    - build
  only:
    - master
