spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}?retryWrites=false

thebutler:
  s3:
    profile: prod
    access-key-id: AKIAWRM5GITXCAO6Y7OB
    secret-access-key: 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
    bucket-fotos: production/butler-fotos
    bucket-documentos: production/butler-documentos
  originsPermitidas: http://localhost:4200,http://localhost:3000,http://localhost:8100,http://localhost:8101,https://thebutler-web.herokuapp.com,file://,http://localhost