spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: the-butler

thebutler:
  s3:
    profile: local
    access-key-id: AKIAWRM5GITXCAO6Y7OB
    secret-access-key: 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
    bucket-fotos: butler-fotos
    bucket-documentos: butler-documentos
  originsPermitidas: http://localhost:4200,http://localhost:3000,https://thebutler-web.herokuapp.com,file://